# Generated by Django 3.2.9 on 2022-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_feedback_last_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='unattended', max_length=12),
        ),
    ]
