# Generated by Django 3.2.9 on 2021-12-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('current_bidder', models.CharField(max_length=20)),
                ('isSold', models.BooleanField()),
                ('listedBy', models.CharField(max_length=20)),
                ('notesByLister', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='image/self.id/')),
                ('image2', models.ImageField(upload_to='image/self.id/')),
                ('image3', models.ImageField(upload_to='image/self.id/')),
                ('image4', models.ImageField(upload_to='image/self.id/')),
                ('image5', models.ImageField(upload_to='image/self.id/')),
            ],
        ),
    ]
