# Generated by Django 3.2.9 on 2022-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_product_listedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isListed',
            field=models.BooleanField(default=False),
        ),
    ]
