# Generated by Django 3.2.9 on 2022-03-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_product_islisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isListed',
        ),
    ]
