# Generated by Django 3.2.9 on 2022-03-02 09:27

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified_address',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=75)),
                ('address_line_two', models.CharField(max_length=75)),
                ('address_line_three', models.CharField(max_length=75)),
                ('address_line_four', models.CharField(max_length=75)),
                ('address_proof', models.FileField(upload_to=account.models.address_upload_handler)),
                ('is_verified', models.BooleanField()),
                ('is_deneyed', models.BooleanField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
