# Generated by Django 3.2.9 on 2022-01-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
