# Generated by Django 3.2.9 on 2022-03-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220302_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User',
            new_name='user',
        ),
    ]
