# Generated by Django 3.2.9 on 2022-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_deneyed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
