# Generated by Django 3.2.9 on 2022-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220302_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_deneyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
